### ISSUE TITLE
Migrate to ESM

### ISSUE THREAD

**Issue by wkillerud** [eik-lib/common#305]
We ought to migrate the internals of this module to ESM. Apart from the Eik CLI (which is being migrated), at time of writing this is the only remaining module on CJS.

**Comment by leftieFriele** [comment]
> Before work is started on this we should decide whether or not to proceed with the current `next` branch and [eik-lib/issues#19](https://github.com/eik-lib/issues/issues/19). The `next` branch is also CJS, but splits the module in several submodules within the same repo.

Not sure what the intension is for splitting it into separate packages, but I think we should focus on converting to ESM and then see if we want to continue with splitting it up.
