### ISSUE TITLE
Invalid file paths ignored without any errors or messaging

### ISSUE THREAD

**Issue by gingermusketeer** [eik-lib/common#83]
I have been changing the setup around for an app and ran into an issue when the asset folder name was changed but I forgot to update the eik.json file. The result was no assets and no indication as to what was wrong.

Adding a console.log to https://github.com/eik-lib/common/blob/f102321cca056486f635881d948c0806de37fd63/lib/helpers/local-assets.js#L26 I saw that the invalid path was being silently dropped by the glob.

Perhaps it would be better to log or raise an error if the glob doesn't match any files?

**Comment by digitalsadhu** [comment]
Yea, I've seen this a bit too. Good point.
